CREATE TABLE fabricantes(
    COD_FABRICANTE NUMBER(3) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2 (15),
    PAIS VARCHAR2 (15),
    CONSTRAINT fabricantes_ck1 CHECK (nombre = UPPER(nombre)),
    CONSTRAINT fabricantes_ck2 CHECK (pais = UPPER(pais))
);

CREATE TABLE articulos (
    COD_ARTICULO VARCHAR2(20) NOT NULL,
    COD_FABRICANTE NUMBER(3) NOT NULL,
    PESO NUMBER(3) NOT NULL,
    CATEGORIA VARCHAR2(10) NOT NULL,
    PRECIO_VENTA NUMBER(4),
    PRECIO_COSTE NUMBER(4),
    EXISTENCIAS NUMBER(5),
    CONSTRAINT articulos_pk PRIMARY KEY (COD_ARTICULO, COD_FABRICANTE, PESO, CATEGORIA),
    CONSTRAINT articulos_fk1 FOREIGN KEY (cod_fabricante) REFERENCES fabricantes,
    CONSTRAINT articulos_ck1 CHECK (peso > 0),
    CONSTRAINT articulos_ck2 CHECK (precio_venta > 0),
    CONSTRAINT articulos_ck3 CHECK (precio_coste > 0),
    CONSTRAINT articulos_ck4 CHECK (categoria in ('primera', 'segunda', 'tercera'))
);

CREATE TABLE tiendas (
    NIF VARCHAR2(10) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2 (29),
    DIRECCION VARCHAR2 (20),
    POBLACION VARCHAR2(20),
    PROVINCIA VARCHAR2 (20),
    COD_POSTAL NUMBER(5),
    CONSTRAINT tiendas_ck1 CHECK (provincia = UPPER(provincia))
);

CREATE TABLE PEDIDOS(
    NIF               VARCHAR2(10) NOT NULL,
    COD_ARTICULO      VARCHAR2(20) NOT NULL,
    COD_FABRICANTE    NUMBER(3) NOT NULL,
    PESO              NUMBER(3) NOT NULL,
    CATEGORIA         VARCHAR2(10) NOT NULL,
    FECHA_PEDIDO      DATE NOT NULL,
    UNIDADES_PEDIDAS  NUMBER(4),
    CONSTRAINT pedidos_pk PRIMARY KEY (NIF, COD_ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_PEDIDO),
    CONSTRAINT pedidos_fk FOREIGN KEY (cod_fabricante) REFERENCES fabricantes,
    CONSTRAINT pedidos_fk2 FOREIGN KEY (COD_ARTICULO, COD_FABRICANTE, PESO,CATEGORIA) REFERENCES ARTICULOS (COD_ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) ON DELETE CASCADE,
    CONSTRAINT pedidos_fk3 FOREIGN KEY (nif) REFERENCES TIENDAS,
    CONSTRAINT pedidos_ck1 CHECK (unidades_pedidas > 0),
    CONSTRAINT pedidos_ck2 CHECK (categoria IN ('primera', 'segunda', 'tercera'))
);

CREATE TABLE VENTAS(
    NIF                VARCHAR2(10) NOT NULL,
    COD_ARTICULO       VARCHAR2(20) NOT NULL,
    COD_FABRICANTE     NUMBER(3) NOT NULL,
    PESO               NUMBER(3) NOT NULL,
    CATEGORIA          VARCHAR2(10) NOT NULL,
    FECHA_VENTA        DATE NOT NULL,
    UNIDADES_VENDIDAS  NUMBER(4),
    CONSTRAINT ventas_pk PRIMARY KEY(NIF,COD_ARTICULO,COD_FABRICANTE, PESO, CATEGORIA, FECHA_VENTA),
    CONSTRAINT ventas_fk FOREIGN KEY (cod_fabricante) REFERENCES fabricantes, 
    CONSTRAINT ventas_fk2 FOREIGN KEY (COD_ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULOS (COD_ARTICULO, COD_FABRICANTE, PESO, CATEGORIA),
    CONSTRAINT ventas_fk3 FOREIGN KEY (nif) REFERENCES tiendas,
    CONSTRAINT ventas_ck1 CHECK (unidades_vendidas > 0),
    CONSTRAINT ventas_ck2 CHECK (categoria IN ('primera', 'segunda', 'tercera'))
);
